stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build

test-job:
  stage: test
  image: node:18
  script:
    - npm install
    - npm run test

deploy-job:
 image: docker:stable
 services:
   - docker:dind
   - node:18-bullseye-slim
 stage: deploy
 variables:
   FLY_API_TOKEN: $FLY_API_TOKEN
 before_script:
 - apk add --update curl && rm -rf /var/cache/apk/*
 - curl -L https://fly.io/install.sh | sh 
 script:
 - /root/.fly/bin/flyctl deploy